config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  resources :inquiry_kinds
  resources :reports
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    delete :sign_out, to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :words
  resources :user_profiles
  get 'top/index'

  get 'error/logout'

  root 'top#index'

  post 'words/page'

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :user
  belongs_to :user_profile, foreign_key: "user_id", primary_key: "user_id"
  has_many :reports
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    # ニックネームも一緒に持ってくる
    @words = Word.where.not(rejected: 1).includes(:user_profile).all
    # logger.debug "word(index) @words => "+@words.pretty_inspect
  end

  # GET /words/1
  # GET /words/1.json
  def show; end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit; end

  # POST /words/page
  def page
    text = 'page:' + params['page'] + ' contain:' + params['contain']
    render text: text
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    if user_signed_in?
      if @word.user_id != current_user.id
        # サインインユーザ以外のことばは編集禁止
        render nothing: true, status: 404
      else
        # ことばの所持ユーザなので編集許可
        respond_to do |format|
          if @word.update(word_params)
            format.html { redirect_to @word, notice: 'Word was successfully updated.' }
            format.json { render :show, status: :ok, location: @word }
          else
            format.html { render :edit }
            format.json { render json: @word.errors, status: :unprocessable_entity }
          end
        end
      end
    else
      # サインイン必須
      render nothing: true, status: 404
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      if user_signed_in? then
        params[:user_id] = current_user.id
      end
      params.permit(:id, :word, :translate, :comment, :age_year, :age_month, :gendar, :user_id, :rejected, :modified, :created, :datetime)
    end
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :translate %><br>
    <%= f.text_field :translate %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :author_nickname %><br>
    <%= f.text_field :author_nickname %>
  </div>
  <div class="field">
    <%= f.label :age_year %><br>
    <%= f.number_field :age_year %>
  </div>
  <div class="field">
    <%= f.label :age_month %><br>
    <%= f.number_field :age_month %>
  </div>
  <div class="field">
    <%= f.label :gendar %><br>
    <%= f.text_field :gendar %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :adopted %><br>
    <%= f.check_box :adopted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<div id="words"></div>

<script type="text/javascript">
  $(function() {
    window.router = new Www.Routers.WordsRouter({words: <%= @words.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<p>
  <strong>Translate:</strong>
  <%= @word.translate %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @word.comment %>
</p>

<p>
  <strong>Author nickname:</strong>
  <%= @word.author_nickname %>
</p>

<p>
  <strong>Age year:</strong>
  <%= @word.age_year %>
</p>

<p>
  <strong>Age month:</strong>
  <%= @word.age_month %>
</p>

<p>
  <strong>Gendar:</strong>
  <%= @word.gendar %>
</p>

<p>
  <strong>Message:</strong>
  <%= @word.message %>
</p>

<p>
  <strong>Adopted:</strong>
  <%= @word.adopted %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>